[package]
name = "mdzk"
version = "0.1.0"
authors = ["Knut Magnus Aasrud <km@aasrud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.10"
mdbook-katex = "0.2.10"
mdbook-wikilink = { git = "https://github.com/ratsclub/mdbook-wikilink" }
quicli = "0.4"
structopt = "0.2"
