[package]
name = "mdzk"
version = "0.1.0"
authors = ["Knut Magnus Aasrud <km@aasrud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.10"
mdbook-katex = "0.2.10"
mdbook-wikilink = { git = "https://github.com/ratsclub/mdbook-wikilink", rev = "497039eeb8088c5a21b1b3bdbf8076bbbdf526f9" }
mdbook-backlinks = { git = "https://github.com/kmaasrud/mdbook-backlinks", branch = "main" }
quicli = "0.4"
structopt = "0.2"
failure = "0.1.8"
futures-util = "0.3.4"
tokio = { version = "0.2.18", features = ["macros"] }
warp = { version = "0.2.2", default-features = false, features = ["websocket"] }
toml = "0.5.8"
notify = "4.0.17"
gitignore = "1.0.7"
