[package]
name = "mdzk"
version = "0.4.3"
authors = [
    "Knut Magnus Aasrud <km@aasrud.com>",
    "Victor Freire <victor@freire.dev.br>",
    "Leo Silva Souza <leovano@protonmail.com>",
    "Xiangru Lian <admin@mail.xrlian.com>",
]
edition = "2021"
description = "Plain text Zettelkasten based on mdBook"
homepage = "https://github.com/mdzk-rs/mdzk"
repository = "https://github.com/mdzk-rs/mdzk"
readme = "README.md"
license-file = "LICENSE"
include = [
    "**/*.rs", 
    "**/*.hbs", 
    "Cargo.toml", 
    "**/*.woff2",
    "**/*.js",
    "**/*.css",
    "**/*.ttf",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
futures-util = "0.3.17"
gray_matter = "0.2.1"
handlebars = "4.1.3"
ignore = "0.4"
lazy-regex = "2.2.1"
mdbook = { version = "0.4.12", default-features = false }
notify = "4.0.17"
pest = "2.1"
pest_derive = "2.1"
pulldown-cmark = { version = "0.8.0", default-features = false, features = ["simd"] }
regex = "1.5.4"
serde = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.23"
toml = "0.5.8"

# Feature: Search
ammonia = "3.1.2"
elasticlunr-rs = { version = "2.3.13", default-features = false }

# Feature: Serve
tokio = { version = "1.11.0", default-features = false, features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3.1", default-features = false, features = ["websocket"] }
