[package]
name = "mdzk"
version = "0.3.3"
authors = [
    "Knut Magnus Aasrud <km@aasrud.com>",
    "Victor Freire <victor@freire.dev.br>",
    "Leo Silva Souza <leovano@protonmail.com>",
    "Xiangru Lian <admin@mail.xrlian.com>",
]
edition = "2018"
description = "Plain text Zettelkasten based on mdBook"
homepage = "https://github.com/mdzk-rs/mdzk"
repository = "https://github.com/mdzk-rs/mdzk"
readme = "README.md"
license-file = "LICENSE"
include = [
    "**/*.rs",
    "Cargo.toml"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.12"
mdbook-katex = "0.2.10"
mdbook-wikilink = "0.3.4"
mdbook-backlinks = "0.2.3"
structopt = "0.2"
futures-util = "0.3.4"
tokio = { version = "0.2.18", features = ["macros"] }
warp = { version = "0.2.2", default-features = false, features = ["websocket"] }
toml = "0.5.8"
notify = "4.0.17"
gitignore = "1.0.7"
walkdir = "2.3.2"
gray_matter = "0.2.0"
serde = "1.0.117"
serde_json = "1.0.59"
regex = "1.4.3"
lazy-regex = "2.2.1"
handlebars = "4.1.2"
log = "0.4.14"
anyhow = "1.0.42"
env_logger = "0.9.0"
elasticlunr-rs = "2.3.13"
pulldown-cmark = "0.7.0"
ammonia = "3.1.2"
chrono = "0.4.19"
