[package]
name = "mdzk"
version = "0.5.0"
authors = [
    "Knut Magnus Aasrud <km@aasrud.com>",
    "Victor Freire <victor@freire.dev.br>",
    "Leo Silva Souza <leovano@protonmail.com>",
    "Xiangru Lian <admin@mail.xrlian.com>",
]
edition = "2021"
description = "Plain text Zettelkasten based on mdBook"
homepage = "https://github.com/mdzk-rs/mdzk"
repository = "https://github.com/mdzk-rs/mdzk"
readme = "README.md"
license-file = "LICENSE"
include = [
    "Cargo.toml", 
    "**/*.rs", 
    "**/*.hbs", 
    "**/*.pest", 
    "**/*.woff2",
    "**/*.js",
    "**/*.css",
    "**/*.ttf",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
chrono = "0.4.19"
futures-util = "0.3.19"
gray_matter = "0.2.1"
handlebars = "4.2.0"
ignore = "0.4.18"
lazy_static = "1.4.0"
lazy-regex = "2.2.2"
mdbook = { version = "0.4.15", default-features = false, features = ["search"] }
notify = "4.0.17"
pest = "2.1.3"
pest_derive = "2.1.0"
pulldown-cmark = { version = "0.9.0", default-features = false, features = ["simd"] }
regex = "1.5.4"
serde = "1.0.133"
serde_json = "1.0.74"
structopt = "0.3.25"
toml = "0.5.8"

# Feature: Search
ammonia = "3.1.2"
elasticlunr-rs = { version = "2.3.14", default-features = false }

# Feature: Serve
tokio = { version = "1.15.0", default-features = false, features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3.2", default-features = false, features = ["websocket"] }
