[book]
authors = ["mdzk-rs"]
language = "en"
multilingual = false
src = "src"
title = "mdzk Documentation"

[build]
build-dir = "out"
create-missing = false

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/mdzk-rs/mdzk"
edit-url-template = "https://github.com/mdzk-rs/mdzk/edit/master/{path}"
no-section-label = false
site-url = "https://mdzk-rs.github.io/mdzk"